[package]
name = "rlox"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
color-eyre = "0.6.5"
memchr = "2.7.6"
memmap2 = "0.9.9"
num_enum = "0.7.5"
thiserror = "2.0.17"

[profile.dev.package.backtrace]
opt-level = 3
